# You may copy this sample config as start point.

[Log]
  ProductionMode = false

[API]
  Port = 3000
  AuditResponse = false

[Postgres]
  Host = ""
  User = ""
  Password = ""
  DatabaseName = ""

[Redis]
  Addr = ""
  Password = ""
  DB = 0
